import { RepairJob } from '../features/repair-management/types';

// 임시 더미 데이터 - 정비 작업 목록
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const DUMMY_REPAIR_JOBS: RepairJob[] = [
  {
    id: '1',
    vehicleId: 'v1',
    vehicleInfo: {
      licensePlate: '12가 3456',
      manufacturer: '현대',
      model: '아반떼',
      year: 2020,
      vin: 'KMHXX00X0XX000001',
    },
    customerInfo: {
      id: 'c1',
      name: '홍길동',
      phone: '010-1234-5678',
      email: 'hong@example.com',
    },
    description: '엔진 체크등 점등, 시동 불량',
    status: 'in_progress',
    type: 'emergency',
    priority: 'high',
    estimatedHours: 3,
    assignedTechnicianId: '2',
    technicianInfo: {
      id: '2',
      name: '이정비',
      role: 'master',
    },
    startDate: '2024-05-21T09:00:00Z',
    completionDate: null,
    createdAt: '2024-05-21T08:30:00Z',
    updatedAt: '2024-05-21T09:00:00Z',
    notes: '실린더 실화 발생, 인젝터 점검 필요',
    cost: {
      labor: 150000,
      parts: 252000,
      total: 402000,
      currency: 'KRW',
    },
    usedParts: [],
    diagnostics: [],
    images: [],
  },
  {
    id: '2',
    vehicleId: 'v2',
    vehicleInfo: {
      licensePlate: '34나 5678',
      manufacturer: '기아',
      model: 'K5',
      year: 2021,
      vin: 'KMHXX00X0XX000002',
    },
    customerInfo: {
      id: 'c2',
      name: '김철수',
      phone: '010-2345-6789',
      email: 'kim@example.com',
    },
    description: '정기 점검 및 오일 교체',
    status: 'pending',
    type: 'regular',
    priority: 'normal',
    estimatedHours: 1,
    assignedTechnicianId: '1',
    technicianInfo: {
      id: '1',
      name: '김기술',
      role: 'senior',
    },
    startDate: null,
    completionDate: null,
    createdAt: '2024-05-21T10:00:00Z',
    updatedAt: '2024-05-21T10:00:00Z',
    notes: '',
    cost: {
      labor: 50000,
      parts: 12000,
      total: 62000,
      currency: 'KRW',
    },
    usedParts: [],
    diagnostics: [],
    images: [],
  },
];
