services:
  postgres:
    image: postgres:14
    container_name: cargoro-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cargoro
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cargoro-core-api
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/cargoro
      - CLERK_SECRET_KEY=${CLERK_SECRET_KEY}
      - JWT_SECRET=${JWT_SECRET:-your-super-secret-key-change-in-production}
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

volumes:
  postgres_data: 