apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    app: {{ .Values.rabbitmq.name }}
    environment: {{ .Values.global.environment }}
spec:
  serviceName: {{ .Values.rabbitmq.name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.rabbitmq.name }}
        environment: {{ .Values.global.environment }}
    spec:
      containers:
        - name: {{ .Values.rabbitmq.name }}
          image: {{ .Values.rabbitmq.image }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: amqp
              containerPort: 5672
              protocol: TCP
            - name: management
              containerPort: 15672
              protocol: TCP
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: {{ .Values.rabbitmq.user | quote }}
            - name: RABBITMQ_DEFAULT_PASS
              value: {{ .Values.rabbitmq.password | quote }}
          resources:
            {{- toYaml .Values.rabbitmq.resources | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.rabbitmq.livenessProbe | nindent 12 }}
          readinessProbe:
            exec:
              command:
                - rabbitmq-diagnostics
                - -q
                - check_running
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: data
              mountPath: /var/lib/rabbitmq
      {{- if .Values.rabbitmq.persistence.enabled }}
      volumes: []
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: {{ .Values.rabbitmq.persistence.storageClass }}
        resources:
          requests:
            storage: {{ .Values.rabbitmq.persistence.size }}
      {{- else }}
      volumes:
        - name: data
          emptyDir: {}
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.rabbitmq.name }}
  labels:
    app: {{ .Values.rabbitmq.name }}
    environment: {{ .Values.global.environment }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.rabbitmq.service.amqpPort }}
      targetPort: amqp
      protocol: TCP
      name: amqp
    - port: {{ .Values.rabbitmq.service.managementPort }}
      targetPort: management
      protocol: TCP
      name: management
  selector:
    app: {{ .Values.rabbitmq.name }}
---
{{- if .Values.networkPolicies.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ .Values.rabbitmq.name }}-network-policy
  labels:
    app: {{ .Values.rabbitmq.name }}
    environment: {{ .Values.global.environment }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Values.rabbitmq.name }}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.apiGateway.name }}
    ports:
    - protocol: TCP
      port: 5672
    - protocol: TCP
      port: 15672
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Values.worker.name }}
    ports:
    - protocol: TCP
      port: 5672
{{- end }}