name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  test-and-coverage:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
    
    - name: pnpm 설정
      uses: pnpm/action-setup@v2
      with:
        version: 8.12.0
    
    - name: Node.js ${{ matrix.node-version }} 설정
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    
    - name: 의존성 설치
      run: pnpm install --frozen-lockfile
    
    - name: 린트 검사
      run: pnpm lint
    
    - name: 타입 체크
      run: pnpm typecheck
    
    - name: 테스트 실행 (Node.js 환경)
      run: pnpm test:coverage
    
    - name: 테스트 실행 (브라우저 환경)
      run: pnpm test:browser
      continue-on-error: true
    
    - name: 커버리지 리포트 업로드
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage/lcov.info,./coverage-browser/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
        verbose: true
    
    - name: 커버리지 코멘트 생성
      uses: 5monkeys/cobertura-action@v13
      if: github.event_name == 'pull_request'
      with:
        path: coverage/clover.xml
        minimum_coverage: 80
        fail_below_threshold: true
        show_line: true
        show_branch: true
        show_missing: true
    
    - name: 빌드 테스트
      run: pnpm build

  lint-and-format:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
    
    - name: pnpm 설정
      uses: pnpm/action-setup@v2
      with:
        version: 8.12.0
    
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'pnpm'
    
    - name: 의존성 설치
      run: pnpm install --frozen-lockfile
    
    - name: Prettier 포맷 검사
      run: pnpm format:check
    
    - name: ESLint 검사
      run: pnpm lint
    
    - name: 라이선스 검사
      run: pnpm licenses list --prod --json > licenses.json
      continue-on-error: true

  security-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: 체크아웃
      uses: actions/checkout@v4
    
    - name: pnpm 설정
      uses: pnpm/action-setup@v2
      with:
        version: 8.12.0
    
    - name: Node.js 설정
      uses: actions/setup-node@v4
      with:
        node-version: 18.x
        cache: 'pnpm'
    
    - name: 의존성 설치
      run: pnpm install --frozen-lockfile
    
    - name: 보안 취약점 검사
      run: pnpm audit --audit-level=high
      continue-on-error: true
    
    - name: 의존성 업데이트 확인
      run: pnpm outdated
      continue-on-error: true
